#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Issei Takei <s20c1709gl@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause

import sys

x = 0.0
for n in sys.argv[1:]:
	x += float(n)

print(x)

