name: test
on: push
jobs:
  test:
   runs-on: ubuntu-latest
   sttategy:
    matrix:
      puthon-version: ["3.7", "3.8", "3.9", "3.10"]
    seteps:
    - uses: actions/checkout@v3
    - name: All test
      run: bash -xv ./plus_stdin

